# Generated by Django 5.1.1 on 2024-10-28 05:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 5, 50, 6, 691989, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usercart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
