# Generated by Django 5.1.1 on 2024-10-28 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_usercart_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 6, 3, 32, 611356, tzinfo=datetime.timezone.utc)),
        ),
    ]
